### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by soundasleep** [soundasleep/html2text_ruby#22]
Hi everyone! I'm no longer a full-time Ruby dev and I've run out of capacity to maintain this project, so I'm looking for some maintainers going forward. Alternatively I can archive the project as read-only.

Ideal criteria:

* You have at least one project on GitHub
* You have experience releasing components to rubygems

Other than that I'm happy for maintainers to take this project into whatever direction it needs to go! :)

For the future of this project I'd suggest some of the most critical tasks are

- [ ] Move CI from travis-ci to Github Actions
- [ ] Set up CI to automatically publish to rubygems
- [ ] Update Gemfile/.lock as necessary e.g. #16

**Comment by krtschmr** [comment]
Just merge the nokogiri bump and everybody is happy :-)

**Comment by Vasfed** [comment]
I'm willing to help with maintaining this project (at least for near future).

Looks like criteria are met: 
- Multiple github projects and experience with github actions CI
- I have multiple gems https://rubygems.org/profiles/Vasfed
- I do full-time ruby development and one of my projects at work has html2text in dependencies

**Comment by shaicoleman** [comment]
@soundasleep, can you please consider transferring ownership to @Vasfed  ?

**Comment by agustin** [comment]
@soundasleep is possible for you to review the offering of @Vasfed?

**Comment by mscrivo** [comment]
@soundasleep has graciously added me as maintainer. I've already merged a few old PRs and cleaned up the codebase a bit. I will publish a new release as soon as I get access to the RubyGems project.
